--Parent
INSERT INTO PRODUCT (DESCRIPTION, NAME, PARENT_PRODUCT)
VALUES ('Boxing','Boxing',null);
INSERT INTO PRODUCT (DESCRIPTION, NAME, PARENT_PRODUCT)
VALUES ('Cricket','Cricket',null);
INSERT INTO PRODUCT (DESCRIPTION, NAME, PARENT_PRODUCT)
VALUES ('Canoeing','Canoeing',null);
--Children 1
INSERT INTO PRODUCT (DESCRIPTION, "NAME", PARENT_PRODUCT)
VALUES ('Boxing Gloves','for hitting people',1);
INSERT INTO PRODUCT (DESCRIPTION, "NAME", PARENT_PRODUCT)
VALUES ('Bag Mitts','for hitting bags',1);
INSERT INTO PRODUCT (DESCRIPTION, "NAME", PARENT_PRODUCT)
VALUES ('Head Guard','protect the old noggin',1);
--Children 2
INSERT INTO PRODUCT (DESCRIPTION, "NAME", PARENT_PRODUCT)
VALUES ('Bat','for hitting balls',2);
INSERT INTO PRODUCT (DESCRIPTION, "NAME", PARENT_PRODUCT)
VALUES ('Box','for protecting balls',2);
--children 3
INSERT INTO PRODUCT (DESCRIPTION, "NAME", PARENT_PRODUCT)
VALUES ('Canadian Canoe','two-man mini boat',3);
--Image
INSERT INTO IMAGE ("TYPE", PRODUCT_ID)  VALUES ('jpg',1);
INSERT INTO IMAGE ("TYPE", PRODUCT_ID)  VALUES ('gif',2);