CREATE TABLE product (
 id INT NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
 name VARCHAR(200),
 description VARCHAR(200),
 parent_product INT
);

ALTER TABLE product ADD CONSTRAINT PK_product PRIMARY KEY (id);


CREATE TABLE image (
 id INT NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
 product_id INT NOT NULL,
 type VARCHAR(50)
);

ALTER TABLE image ADD CONSTRAINT PK_image PRIMARY KEY (id);
ALTER TABLE product ADD CONSTRAINT FK_product_0 FOREIGN KEY (parent_product) REFERENCES product (id);
ALTER TABLE image ADD CONSTRAINT FK_image_0 FOREIGN KEY (product_id) REFERENCES product (id);
